name: Build

on:
  workflow_dispatch:


defaults:
  run:
    shell: bash


env:
  DOCKER_REPO_NAME: gitea-act-runner
  HUAWEICLOUD_IAM_AK: "${{ secrets.HUAWEICLOUD_IAM_AK }}"
  HUAWEICLOUD_IAM_SK: "${{ secrets.HUAWEICLOUD_IAM_SK }}"


permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 45

    permissions:
      packages: write

    env:
      TZ: Asia/Shanghai

    steps:
    - name: Git Checkout
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0


    - name: Login to ghcr.io
      uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee # v4.2.0
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}


    # - name: Login to SWR
    #   run: docker login -u cn-southwest-2@$HUAWEICLOUD_IAM_AK -p $HUAWEICLOUD_IAM_SK swr.cn-southwest-2.myhuaweicloud.com


    - name: Build and Push
      env:
        DOCKER_BASE_IMAGE: ubuntu:24.04
        DOCKER_IMAGE_REPO: ${{ github.repository_owner }}/${{ env.DOCKER_REPO_NAME }}
      run: |
        set -exuo pipefail

        function push_to_registry() {
          local target="$1:$IMAGE_TAG"
          echo "Tagging [$image_name] -> [$target]"
          docker tag "$image_name" "$target"
          echo "Pushing [$target]"
          docker push "$target"
        }

        # resolve gitea act runner version (latest stable release)
        gitea_runner_effective_version=$(curl -sSf 'https://gitea.com/api/v1/repos/gitea/runner/releases?draft=false&pre-release=false&limit=1' | jq -r '.[0].tag_name | ltrimstr("v")')

        IMAGE_TAG="$(date +'%Y%m%d_%H%M%S')-x86_64"
        image_name="$DOCKER_IMAGE_REPO:$IMAGE_TAG"

        # build the image
        echo "Building docker image [$image_name]..."
        docker build \
          --file "gitea-act-runner/Dockerfile" \
          --progress=plain \
          --pull \
          --build-arg BASE_IMAGE="$DOCKER_BASE_IMAGE" \
          --build-arg GITEA_RUNNER_VERSION="$gitea_runner_effective_version" \
          -t "$image_name" .

        # test image
        echo "Testing docker image [$image_name]..."
        docker run --pull=never --rm "$image_name" gitea-runner --version

        echo "Listing docker images..."
        docker images
        docker history "$image_name"

        # push to ghcr.io
        push_to_registry "ghcr.io/$DOCKER_IMAGE_REPO"

        # push to SWR
        # swr_registry=swr.cn-southwest-2.myhuaweicloud.com
        # swr_namespace=gsc-hub
        # swr_image_name="${DOCKER_IMAGE_REPO##*/}"
        # push_to_registry "$swr_registry/$swr_namespace/$swr_image_name"
